const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const gains=[],sources=[],button={dataset:{},setAttribute(){} };let audio,tick;
class Context{constructor(){audio=this;this.currentTime=0;this.destination={};}async resume(){this.state='running';}async suspend(){this.state='suspended';}async close(){}async decodeAudioData(){return {length:960000,duration:20};}createGain(){const node={connect(){},disconnect(){},gain:{value:1,events:[],setValueAtTime(v,t){this.events.push(['value',v,t]);},setValueCurveAtTime(v,t,d){this.events.push(['curve',Array.from(v),t,d]);},setTargetAtTime(v){this.value=v;}}};gains.push(node);return node;}createBufferSource(){const node={connect(){},disconnect(){},start(t){this.startTime=t;},stop(t){this.endTime=t;}};sources.push(node);return node;}}
const window={AudioContext:Context};vm.runInNewContext(fs.readFileSync('Light-Surf-dev/src/soundtrack.js','utf8'),{window,document:{getElementById:id=>id==='music'?button:{textContent:JSON.stringify({tracks:[{title:'Plastic',bed:'AA==',rhythm:'AA=='},{title:'Watching',bed:'AA==',rhythm:'AA=='}]})}},Uint8Array,Float32Array,atob,setInterval:f=>(tick=f,1),clearInterval(){}});
await window.soundtrack.start();assert.equal(button.dataset.trackCount,'2');assert.equal(button.dataset.aligned,'true');assert.equal(sources[0].startTime,sources[1].startTime);assert(Math.abs(sources[0].endTime-sources[2].startTime-4)<1e-8);
const out=gains[2].gain.events.find(x=>x[0]==='curve')[1],inc=gains[4].gain.events.find(x=>x[0]==='curve')[1];for(let i=0;i<128;i++)assert(Math.abs(out[i]**2+inc[i]**2-1)<1e-6);
window.soundtrack.setGrounded(false);assert.equal(gains[1].gain.value,0);window.soundtrack.setGrounded(true);assert.equal(gains[1].gain.value,1);
window.soundtrack.setPaused(true);await Promise.resolve();assert.equal(audio.state,'suspended');window.soundtrack.setPaused(false);await Promise.resolve();assert.equal(audio.state,'running');button.onclick();assert.equal(gains[0].gain.value,0);
audio.currentTime=100;tick();assert(sources.at(-1).endTime>140);assert.equal(button.dataset.crossfadeSeconds,'4');console.log('PASS: equal-power four-second overlap, synchronized stems, playlist replenishment, airborne mix, pause and mute');
const cp=require('node:child_process');const baseline=cp.execFileSync('git',['-C','Light-Surf-dev','show','f88a2f6:index.html'],{maxBuffer:30e6}).toString().replace(/\r\n/g,'\n');const built=fs.readFileSync('Light-Surf-dev/index.html','utf8');const gameplay=s=>s.slice(s.indexOf("'use strict';\n(() => {\nconst $="));const physics=s=>s.slice(s.indexOf('const Physics ='),s.indexOf("'use strict';\n(() => {\n const button="));assert.equal(gameplay(baseline),gameplay(built));assert.equal(physics(baseline),physics(built));console.log('PASS: uploaded gameplay, physics and renderer unchanged');
})();
