const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),P=require('../src/physics.js');
const root=path.resolve(__dirname,'..');
function input(mode){return {steer:mode===2?.45:0,drive:mode===3?1:0,crouch:[1,2,4].includes(mode)};}
const reference=fs.readFileSync(path.join(__dirname,'reference.txt'),'utf8').trim().split(/\r?\n/).map(l=>l.split(/\s+/).map(Number));let maxDelta=0;
for(let mode=0;mode<5;mode++){const s=P.reset();if(mode===4){s.position.y+=.4;s.velocity.y=-110;s.grounded=false;}for(let i=1;i<=360;i++){P.step(s,input(mode));const row=reference.find(r=>r[0]===mode&&r[1]===i);if(row){const values=[s.position.x,s.position.y,s.position.z,s.velocity.y,s.speed,s.sink,s.launches,s.landings];values.forEach((v,k)=>{const error=Math.abs(v-row[k+2]);maxDelta=Math.max(maxDelta,error);assert(error<(k>=6?.1:.08),`C comparison mode=${mode} tick=${i} field=${k}: JS ${v} vs C ${row[k+2]}`);});}}}
console.log('PASS: 20 archived-C snapshots: neutral, grip, carving, dive and hard landing; maximum difference',maxDelta.toFixed(6));
const s=P.reset();s.position.y+=.4;s.velocity.y=-110;s.grounded=false;const vy=s.velocity.y-18/120,y=s.position.y+vy/120;P.step(s,{steer:0,drive:0,crouch:true});assert(s.grounded);assert(Math.abs(s.velocity.y-vy)<1e-8);assert(Math.abs(s.position.y-y)<1e-8);let maxSink=0;for(let i=0;i<240;i++){P.step(s,{steer:0,drive:0,crouch:true});maxSink=Math.max(maxSink,s.sink);assert(s.sink>=-1.2&&s.sink<=12);}assert(maxSink>3&&maxSink<8);console.log('PASS: continuous touchdown and buoyancy recovery; dip',maxSink.toFixed(2));
for(const mode of [0,1,2]){const s=P.reset();for(let i=0;i<36000;i++){P.step(s,input(mode));for(const axis of ['x','z'])if(Math.abs(s.position[axis])>4096)P.rebase(s,axis==='x'?Math.sign(s.position.x)*8192:0,axis==='z'?Math.sign(s.position.z)*8192:0);assert(Object.values(s.position).every(Number.isFinite));assert(s.speed>=60&&s.speed<=220);}if(mode===1)assert.equal(s.launches,0);if(mode===0)assert(s.launches>20&&s.landings>20);console.log(`PASS: five-minute mode ${mode}, ${s.launches} launches / ${s.landings} landings`);}
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert(!/<(?:script|link)[^>]+(?:src|href)=/i.test(html));assert(!/\/\* (PHYSICS|RENDERER|GAME) \*\//.test(html));console.log('PASS: standalone HTML has all code inline and no external dependencies');
