'use strict';
(() => {
const $=id=>document.getElementById(id),canvas=$('game'),keys=new Set();let state=Physics.reset(),renderer,paused=true,started=false,starting=false,debug=false,intro=6,accumulator=0,previous=0,fps=60,lastButtons=[],touch={steer:0,drive:0,crouch:false},running=true;
function fail(message){$('error').textContent=message;$('error').hidden=false;running=false;}
try{renderer=new SurfRenderer(canvas);renderer.reset(state);}catch(e){fail(e.message);return;}
function setPause(value){paused=value;window.soundtrack?.setPaused(value);accumulator=0;$('pause').textContent=paused?'Resume':'Pause';$('pause').setAttribute('aria-label',paused?'Resume game':'Pause game');$('paused').hidden=!started||!paused;$('help').classList.toggle('hidden',!started||(!paused&&intro<=0));}
async function start(){if(started||starting)return;starting=true;$('start').disabled=true;$('start').textContent='Starting…';await window.soundtrack?.start();started=true;starting=false;previous=0;$('start-screen').hidden=true;$('toolbar').hidden=false;$('touch').hidden=false;setPause(document.hidden);canvas.focus();}
$('start').onclick=start;$('toolbar').hidden=true;$('touch').hidden=true;
function reset(){state=Physics.reset();renderer.reset(state);accumulator=0;intro=6;}
function action(code){if(!started)return;if(code==='Escape'||code==='KeyP')setPause(!paused);if(code==='KeyR')reset();if(code==='KeyL'){debug=!debug;$('debug').hidden=!debug;}}
const handled=new Set(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD','KeyZ','KeyQ','KeyE','Digit1','Digit2','KeyP','KeyR','KeyL','Escape']);
window.addEventListener('keydown',e=>{if(!started){if(e.code==='Enter'||e.code==='Space'){e.preventDefault();void start();}return;}if(!handled.has(e.code)||e.ctrlKey||e.metaKey||e.altKey)return;if(e.target instanceof HTMLButtonElement&&(e.code==='Space'))return;e.preventDefault();keys.add(e.code);if(!e.repeat)action(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));
function clearInputs(){keys.clear();touch={steer:0,drive:0,crouch:false};$('nub').style.transform='';$('grip').classList.remove('active');}
window.addEventListener('blur',()=>{clearInputs();setPause(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInputs();setPause(true);}previous=0;});
$('pause').onclick=()=>setPause(!paused);$('reset').onclick=reset;$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){$('fullscreen').title='Fullscreen is unavailable in this browser.';}};
const pad=$('pad');let pointer=null;function move(e){if(e.pointerId!==pointer)return;const r=pad.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/45,y=(e.clientY-r.top-r.height/2)/45,n=Math.max(1,Math.hypot(x,y));touch.steer=x/n;touch.drive=-y/n;$('nub').style.transform=`translate(${touch.steer*40}px,${-touch.drive*40}px)`;}
pad.onpointerdown=e=>{pointer=e.pointerId;pad.setPointerCapture(pointer);move(e);};pad.onpointermove=move;pad.onpointerup=pad.onpointercancel=pad.onlostpointercapture=()=>{pointer=null;touch.steer=touch.drive=0;$('nub').style.transform='';};$('grip').onpointerdown=e=>{e.currentTarget.setPointerCapture(e.pointerId);touch.crouch=true;$('grip').classList.add('active');};$('grip').onpointerup=$('grip').onpointercancel=$('grip').onlostpointercapture=()=>{touch.crouch=false;$('grip').classList.remove('active');};
const down=(...codes)=>codes.some(c=>keys.has(c)),analog=x=>Math.abs(x)<.12?0:Math.sign(x)*(Math.abs(x)-.12)/.88;
function controls(){let steer=Number(down('ArrowRight','KeyD'))-Number(down('ArrowLeft','KeyA'))+touch.steer,drive=Number(down('ArrowUp','KeyW'))-Number(down('ArrowDown','KeyS'))+touch.drive,crouch=down('Space','KeyZ')||touch.crouch,orbit=(Number(down('KeyE'))-Number(down('KeyQ')))*.65,distance=down('Digit1')?70:down('Digit2')?132:92;const pad=Array.from(navigator.getGamepads?.()||[]).find(p=>p&&p.mapping==='standard');if(pad){steer+=analog(pad.axes[0]||0);drive-=analog(pad.axes[1]||0);crouch||=!!pad.buttons[6]?.pressed;orbit+=analog(pad.axes[2]||0)*.65;const y=analog(pad.axes[3]||0);if(y<-.2)distance=70;if(y>.2)distance=132;for(const [b,code]of [[9,'Escape'],[5,'KeyR'],[4,'KeyL']])if(pad.buttons[b]?.pressed&&!lastButtons[b])action(code);lastButtons=pad.buttons.map(b=>b.pressed);}else lastButtons=[];return {steer,drive,crouch,orbit,distance};}
function frame(now){if(!running)return;const elapsed=previous?Math.min((now-previous)/1000,.1):0;previous=now;if(elapsed>0)fps+=(1/elapsed-fps)*.05;const input=started?controls():{steer:0,drive:0,crouch:false,orbit:0,distance:92};if(!paused){accumulator+=elapsed;while(accumulator>=1/120){Physics.step(state,input);accumulator-=1/120;}for(const axis of ['x','z'])if(Math.abs(state.position[axis])>4096){const shift=state.position[axis]>0?8192:-8192;Physics.rebase(state,axis==='x'?shift:0,axis==='z'?shift:0);renderer.eye[axis==='x'?0:2]-=shift;}renderer.update(state,elapsed,input.orbit,input.distance);intro-=elapsed;}$('help').classList.toggle('hidden',!started||(!paused&&intro<=0));window.soundtrack?.setGrounded(state.grounded);window.soundtrack?.setSubmersion(Physics.clamp((state.sink-2.5)/3,0,1));renderer.render(state);if(debug)$('debug').textContent=`${fps.toFixed(1)} FPS   ${renderer.drawMs.toFixed(1)} DRAW ms\n${state.grounded?'SURF':'AIR'}   SPEED ${state.speed.toFixed(0)}   GRIP ${input.crouch?'ON':'OFF'}\nHEADING ${state.heading.toFixed(3)}   LEAN ${state.lean.toFixed(3)}\nLAUNCH ${state.launches}   LAND ${state.landings}\nR7 WEB · 120 Hz physics`;requestAnimationFrame(frame);}
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fail('Graphics context lost. Reload this page to return to the ocean.');});
// Read-only snapshot for diagnostics and browser validation.
window.lightSurf={snapshot:()=>({state:JSON.parse(JSON.stringify(state)),paused,fps,drawMs:renderer.drawMs,triangles:renderer.triangles}),version:'R7 web 1'};
requestAnimationFrame(frame);
})();
