'use strict';
/* WebGL replaces the N64 triangle submission; geometry, palette and camera
   retain R7's original equations and 25 x 25 nonuniform ocean mesh. */
class SurfRenderer {
 constructor(canvas){this.canvas=canvas;const gl=this.gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)throw Error('WebGL is unavailable. Enable hardware acceleration or try another browser.');
 const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
 const p=this.program=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,'attribute vec3 position; attribute vec3 color; varying vec3 tint; uniform float screenSpace; void main(){ tint=color; if(screenSpace>0.5)gl_Position=vec4(position,1.0);else gl_Position=vec4(position.x*1.1875,position.y*1.5833333,position.z-12.0,position.z); }'));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,'precision mediump float; varying vec3 tint; void main(){gl_FragColor=vec4(tint,1.0);}'));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));gl.useProgram(p);this.buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer);for(const [name,offset] of [['position',0],['color',12]]){const l=gl.getAttribLocation(p,name);gl.enableVertexAttribArray(l);gl.vertexAttribPointer(l,3,gl.FLOAT,false,24,offset);}this.mode=gl.getUniformLocation(p,'screenSpace');
 this.offset=[-640,-512,-400,-312,-240,-184,-136,-96,-64,-40,-24,-8,0,8,24,40,64,96,136,184,240,312,400,512,640];this.shape=[[0,12],[3.8,5],[3.2,-10],[0,-12],[-3.2,-10],[-3.8,5]];this.stars=[];let seed=71;for(let i=0;i<42;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const az=(seed&65535)*Math.PI*2/65536;seed=(Math.imul(seed,1664525)+1013904223)>>>0;this.stars.push([Math.sin(az),.15+(seed&255)*.003,Math.cos(az)]);}this.distance=92;
 }
 reset(s){this.yaw=s.heading;this.eye=[s.position.x,s.position.y+40,s.position.z-92];this.distance=92;}
 update(s,dt,orbit=0,distance=92){let delta=s.heading+orbit-this.yaw;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;this.yaw+=delta*Physics.clamp(2.6*dt,0,1);this.yaw=Math.atan2(Math.sin(this.yaw),Math.cos(this.yaw));const altitude=Math.max(0,s.position.y-Physics.surface(s,s.position.x,s.position.z).height-2.5);distance+=Math.min(altitude*.65,95);this.distance+=(distance-this.distance)*Physics.clamp(3*dt,0,1);const desired=[s.position.x-Math.sin(this.yaw)*this.distance,s.position.y+36+this.distance*.06,s.position.z-Math.cos(this.yaw)*this.distance];this.eye=V.add(this.eye,V.mul(V.sub(desired,this.eye),Physics.clamp(5*dt,0,1)));this.eye[1]=Math.max(this.eye[1],Physics.surface(s,this.eye[0],this.eye[2]).height+14);}
 camera(p,color){const d=V.sub(p,this.eye);return [V.dot(d,this.right),V.dot(d,this.up),V.dot(d,this.forward),...color];}
 sky(y){const elevation=this.forward[1]+(120-y)/190*this.up[1],haze=(1-Physics.clamp(elevation/.7,0,1))**2,night=[10/255,13/255,34/255],glow=Physics.clamp(1-Math.abs(elevation-.035)/.18,0,1)**2;return V.add(V.add(night,V.mul(V.sub(this.haze,night),haze)),V.mul([.16,.20,.19],glow));}
 draw(data,screen=false){const gl=this.gl;gl.uniform1f(this.mode,screen?1:0);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,data.length/6);}
 render(s){const start=performance.now(),gl=this.gl;gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const altitude=Math.max(0,s.position.y-Physics.surface(s,s.position.x,s.position.z).height-2.5),target=[s.position.x+Math.sin(this.yaw)*24,s.position.y+5-Math.min(altitude*.4,70),s.position.z+Math.cos(this.yaw)*24];this.forward=V.unit(V.sub(target,this.eye));this.right=V.unit(V.cross([0,1,0],this.forward));this.up=V.cross(this.forward,this.right);const sunset=Physics.clamp((this.forward[0]*.25+this.forward[2]*.97+1)*.5,0,1);this.haze=[(40+32*sunset)/255,(62-8*sunset)/255,(88-8*sunset)/255];
 let data=[];const screen=(x,y,c)=>[x/160-1,1-y/120,0,...c],tri=(a,b,c)=>data.push(...a,...b,...c);gl.disable(gl.DEPTH_TEST);
 for(let y=0;y<240;y+=30){const a=screen(0,y,this.sky(y)),b=screen(320,y,this.sky(y)),c=screen(320,y+30,this.sky(y+30)),d=screen(0,y+30,this.sky(y+30));tri(a,b,c);tri(a,c,d);}
 const sun=V.unit([.26,.045,1]),sunz=V.dot(sun,this.forward);if(sunz>.2){const x=160+190*V.dot(sun,this.right)/sunz,y=120-190*V.dot(sun,this.up)/sunz,r=34/sunz;for(let i=0;i<40;i++){const a=i*Math.PI/20,b=(i+1)*Math.PI/20;tri(screen(x,y,[1,.39,.56]),screen(x+Math.cos(a)*r,y+Math.sin(a)*r,[1,.34+.13*Math.sin(a),.51+.12*Math.sin(a)]),screen(x+Math.cos(b)*r,y+Math.sin(b)*r,[1,.34+.13*Math.sin(b),.51+.12*Math.sin(b)]));}}
 for(const star of this.stars){const z=V.dot(star,this.forward);if(z<=.1)continue;const x=160+190*V.dot(star,this.right)/z,y=120-190*V.dot(star,this.up)/z;if(x>1&&x<318&&y>1&&y<90){const c=[150/255,162/255,189/255],a=screen(x,y,c),b=screen(x+1,y,c),d=screen(x,y+1,c),e=screen(x+1,y+1,c);tri(a,b,e);tri(a,e,d);}}
 this.draw(data,true);data=[];gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);
 const grid=[],heights=[];for(let z=0;z<25;z++){grid[z]=[];heights[z]=[];for(let x=0;x<25;x++){const wx=s.position.x+this.offset[x],wz=s.position.z+this.offset[z],w=Physics.surface(s,wx,wz);heights[z][x]=w.height;const n=V.unit([-w.dx,1,-w.dz]),light=Physics.clamp(-n[0]*.4+n[1]*.6-n[2]*.69,0,1)**2,crest=Physics.clamp((w.height+40)/100,0,1),foam=Physics.clamp(w.wake*.11,0,.48);let color=[.055+.32*crest+.12*light,.035+.82*light,.16+.74*light];color=V.add(color,V.mul(V.sub([.5,.93,1],color),foam));const v=this.camera([wx,w.height,wz],color),band=Physics.clamp((v[2]-120)/100,0,1)*Physics.clamp((440-v[2])/120,0,1),fill=band*(.35+.65*light);color=V.add(color,V.mul([.18,.32,.26],fill)).map(c=>Physics.clamp(c,0,1));const fog=Physics.clamp((v[2]-280)/210,0,1);if(fog>0)color=V.add(color,V.mul(V.sub(this.sky(120-190*v[1]/v[2]),color),fog));grid[z][x]=[...v.slice(0,3),...color];}}
 for(let z=0;z<24;z++)for(let x=0;x<24;x++){tri(grid[z][x],grid[z+1][x],grid[z+1][x+1]);tri(grid[z][x],grid[z+1][x+1],grid[z][x+1]);}
 const meshHeight=(x,z)=>{const lx=x-s.position.x,lz=z-s.position.z;let ix=0,iz=0;while(ix<23&&this.offset[ix+1]<lx)ix++;while(iz<23&&this.offset[iz+1]<lz)iz++;const u=Physics.clamp((lx-this.offset[ix])/(this.offset[ix+1]-this.offset[ix]),0,1),v=Physics.clamp((lz-this.offset[iz])/(this.offset[iz+1]-this.offset[iz]),0,1),a=heights[iz][ix],c=heights[iz+1][ix+1];return v>=u?a*(1-v)+heights[iz+1][ix]*(v-u)+c*u:a*(1-u)+c*v+heights[iz][ix+1]*(u-v);};
 const fx=Math.sin(s.heading),fz=Math.cos(s.heading),size=1.35+Physics.clamp(altitude/200,0,.5),middle=this.camera([s.position.x,meshHeight(s.position.x,s.position.z)+.8,s.position.z],[.025,.018,.07]),inner=[],outer=[];
 for(const [bx,bz] of this.shape){const sideways=bx*Math.cos(s.lean)*size,along=bz*Math.cos(s.pitch)*size,x=s.position.x+fz*sideways+fx*along,z=s.position.z-fx*sideways+fz*along;outer.push(this.camera([x,meshHeight(x,z)+.8,z],[.14,.1,.25]));const ix=s.position.x+(x-s.position.x)*.7,iz=s.position.z+(z-s.position.z)*.7;inner.push(this.camera([ix,meshHeight(ix,iz)+.9,iz],[.035,.025,.09]));}for(let i=0;i<6;i++){const j=(i+1)%6;tri(middle,inner[i],inner[j]);tri(inner[i],outer[i],outer[j]);tri(inner[i],outer[j],inner[j]);}
 const f=[fx*Math.cos(s.pitch),Math.sin(s.pitch),fz*Math.cos(s.pitch)],r0=[fz,0,-fx],n=V.unit(V.cross(f,r0)),r=V.add(V.mul(r0,Math.cos(s.lean)),V.mul(n,Math.sin(s.lean))),center=[s.position.x,s.position.y+1.5,s.position.z],top=[],bottom=[];
 for(const [x,z]of this.shape){const p=V.add(center,V.add(V.mul(r,x),V.mul(f,z)));top.push(this.camera(p,[.96,.91,.91]));bottom.push(this.camera(V.sub(p,V.mul(n,1.7)),[.28,.13,.36]));}for(let i=1;i<5;i++)tri(top[0],top[i],top[i+1]);for(let i=0;i<6;i++){const j=(i+1)%6;tri(top[i],bottom[i],bottom[j]);tri(top[i],bottom[j],top[j]);}
 const point=(x,z,h,color)=>this.camera(V.add(center,V.add(V.mul(r,x),V.add(V.mul(f,z),V.mul(n,h)))),color);tri(point(0,9,.25,[1,.24,.53]),point(2.4,0,.25,[1,.24,.53]),point(-2.4,0,.25,[1,.24,.53]));for(const z of [3,-5]){const p=[[-2,-1.6],[2,-1.6],[2,1.6],[-2,1.6]].map(([x,d])=>point(x,z+d,.35,[.11,.08,.19]));tri(p[0],p[1],p[2]);tri(p[0],p[2],p[3]);}
 this.draw(data);this.triangles=data.length/18;this.drawMs=performance.now()-start;
 }
}
const V={add:(a,b)=>a.map((v,i)=>v+b[i]),sub:(a,b)=>a.map((v,i)=>v-b[i]),mul:(a,s)=>a.map(v=>v*s),dot:(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],unit:a=>{const n=Math.hypot(...a);return a.map(v=>v/n);}};
